#ifndef UI_HTML_H
#define UI_HTML_H

static const char UI_HTML[] =
    "<!DOCTYPE html>\n"
    "<html>\n"
    "<head>\n"
    "<meta charset='utf-8'>\n"
    "<style>\n"
    "  :root {\n"
    "    --bg:#1a1b1d; --surface:#232427; --surface-2:#2c2e31; --border:#3a3c40;\n"
    "    --text:#eceef0; --text-dim:#9a9da2; --accent:#3ecf6e; --accent-hover:#34b860;\n"
    "    --ok-bg:#173a26; --ok-fg:#7ee8a0; --err-bg:#3a1a1e; --err-fg:#ff9aa3;\n"
    "    --radius:10px; --radius-sm:7px;\n"
    "  }\n"
    "  * { box-sizing:border-box; }\n"
    "  html, body { height:100%; overflow:hidden; }\n"
    "  body {\n"
    "    font-family: 'Segoe UI', system-ui, -apple-system, sans-serif;\n"
    "    background: var(--bg);\n"
    "    color: var(--text); margin:0; padding:14px; font-size:13px;\n"
    "    -webkit-font-smoothing:antialiased;\n"
    "    display:flex; flex-direction:column; height:100%;\n"
    "  }\n"
    "  select, input, button, textarea { font-family: inherit; }\n"
    "  label { color:var(--text-dim); font-size:12px; letter-spacing:.2px; }\n"
    "  .row { display:flex; gap:8px; align-items:center; margin-bottom:10px; flex-shrink:0; }\n"
    "  select {\n"
    "    flex:1; background:var(--surface); color:var(--text); border:1px solid var(--border);\n"
    "    padding:7px 8px; border-radius:var(--radius-sm); outline:none; transition:border-color .15s ease;\n"
    "    appearance:none; -webkit-appearance:none;\n"
    "    background-image:url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' width='12' height='12'%3E%3Cpath fill='%239a9da2' d='M7 10l5 5 5-5z'/%3E%3C/svg%3E\");\n"
    "    background-repeat:no-repeat; background-position:right 8px center; padding-right:26px;\n"
    "  }\n"
    "  select:hover { border-color:#4a4d51; }\n"
    "  select:focus { border-color:var(--accent); }\n"
    "  select:disabled { opacity:.5; }\n"
    "  select option {\n"
    "    background:var(--surface); color:var(--text); padding:6px;\n"
    "  }\n"
    "  select option:checked, select option:hover {\n"
    "    background:var(--accent); color:#fff;\n"
    "  }\n"
    "  select.native-select {\n"
    "    position:absolute; width:1px; height:1px; padding:0; margin:-1px; overflow:hidden;\n"
    "    clip:rect(0,0,0,0); white-space:nowrap; border:0; opacity:0; pointer-events:none;\n"
    "  }\n"
    "  .dropdown { position:relative; flex:1; }\n"
    "  .dropdown-trigger {\n"
    "    width:100%; display:flex; align-items:center; justify-content:space-between; gap:8px;\n"
    "    background:var(--surface); color:var(--text); border:1px solid var(--border);\n"
    "    padding:7px 10px; border-radius:var(--radius-sm); font-size:13px; text-align:left;\n"
    "    transition:border-color .15s ease, background .15s ease;\n"
    "  }\n"
    "  .dropdown-trigger span { overflow:hidden; text-overflow:ellipsis; white-space:nowrap; }\n"
    "  .dropdown-trigger:hover { border-color:#4a4d51; background:var(--surface); transform:none; box-shadow:none; }\n"
    "  .dropdown-trigger .chevron { width:12px; height:12px; fill:var(--text-dim); flex-shrink:0; transition:transform .15s ease; }\n"
    "  .dropdown.open .dropdown-trigger { border-color:var(--accent); }\n"
    "  .dropdown.open .chevron { transform:rotate(180deg); }\n"
    "  .dropdown-trigger:disabled { opacity:.5; cursor:default; }\n"
    "  .dropdown-menu {\n"
    "    position:absolute; top:calc(100% + 6px); left:0; right:0; z-index:50;\n"
    "    background:var(--surface-2); border:1px solid var(--border); border-radius:var(--radius-sm);\n"
    "    max-height:180px; overflow-y:auto; box-shadow:0 10px 24px rgba(0,0,0,.45);\n"
    "    display:none; padding:4px;\n"
    "  }\n"
    "  .dropdown-menu::-webkit-scrollbar { width:6px; }\n"
    "  .dropdown-menu::-webkit-scrollbar-thumb { background:var(--border); border-radius:3px; }\n"
    "  .dropdown.open .dropdown-menu { display:block; }\n"
    "  .dropdown-item {\n"
    "    padding:7px 9px; border-radius:6px; cursor:pointer; font-size:12px; color:var(--text);\n"
    "    overflow:hidden; text-overflow:ellipsis; white-space:nowrap; transition:background .1s ease;\n"
    "  }\n"
    "  .dropdown-item:hover, .dropdown-item.highlighted { background:var(--accent); color:#fff; }\n"
    "  .dropdown-item.selected { color:var(--accent); font-weight:600; }\n"
    "  .dropdown-item.selected:hover, .dropdown-item.selected.highlighted { color:#fff; }\n"
    "  .dropdown-empty { padding:8px 9px; font-size:12px; color:var(--text-dim); }\n"
    "  .tabs {\n"
    "    display:flex; gap:2px; background:var(--surface); padding:3px; border-radius:var(--radius);\n"
    "    margin-bottom:12px; border:1px solid var(--border); flex-shrink:0;\n"
    "  }\n"
    "  .tab {\n"
    "    flex:1; text-align:center; padding:6px 8px; cursor:pointer; user-select:none;\n"
    "    color:var(--text-dim); font-size:12px; border-radius:var(--radius-sm);\n"
    "    transition: background .15s ease, color .15s ease;\n"
    "  }\n"
    "  .tab:hover { color:var(--text); }\n"
    "  .tab.active { background:var(--accent); color:#fff; }\n"
    "  .panel { display:none; animation: fadeIn .15s ease; }\n"
    "  .panel.active {\n"
    "    display:flex; flex-direction:column; flex:1 1 auto; min-height:0; overflow-y:auto;\n"
    "  }\n"
    "  .panel.active::-webkit-scrollbar { width:6px; }\n"
    "  .panel.active::-webkit-scrollbar-thumb { background:var(--border); border-radius:3px; }\n"
    "  @keyframes fadeIn { from { opacity:0; transform:translateY(2px); } to { opacity:1; transform:translateY(0); } }\n"
    "  button {\n"
    "    background:var(--surface-2); color:var(--text); border:1px solid var(--border);\n"
    "    border-radius:var(--radius-sm); padding:7px 16px; cursor:pointer; font-size:12px;\n"
    "    font-weight:500; transition: background .15s ease, transform .12s cubic-bezier(.34,1.56,.64,1),\n"
    "      box-shadow .18s ease, border-color .15s ease;\n"
    "    will-change: transform;\n"
    "  }\n"
    "  button:hover { background:#33363b; border-color:#4d5157; transform:translateY(-1px); box-shadow:0 4px 12px rgba(0,0,0,.35); }\n"
    "  button:active { transform:translateY(0) scale(0.95); box-shadow:0 1px 4px rgba(0,0,0,.3); transition-duration:.05s; }\n"
    "  #btnImport, #btnExport, #btnSavePreset {\n"
    "    background:var(--accent); border-color:var(--accent); color:#fff;\n"
    "  }\n"
    "  #btnImport:hover, #btnExport:hover, #btnSavePreset:hover {\n"
    "    background:var(--accent-hover); border-color:var(--accent-hover);\n"
    "    transform:translateY(-1px); box-shadow:none;\n"
    "  }\n"
    "  #btnImport:active, #btnExport:active, #btnSavePreset:active {\n"
    "    transform:translateY(0) scale(0.95); box-shadow:none;\n"
    "  }\n"
    "  textarea, input[type=text] {\n"
    "    width:100%; background:var(--surface); color:var(--text); border:1px solid var(--border);\n"
    "    border-radius:var(--radius-sm); padding:8px; outline:none; transition:border-color .15s ease;\n"
    "  }\n"
    "  textarea:focus, input[type=text]:focus { border-color:var(--accent); }\n"
    "  input[type=text]::placeholder { color:var(--text-dim); }\n"
    "  .toast {\n"
    "    position:fixed; top:-40px; left:14px; right:14px; padding:8px 10px; border-radius:var(--radius-sm);\n"
    "    font-size:12px; text-align:center; font-weight:500; transition: top 0.25s cubic-bezier(.34,1.56,.64,1);\n"
    "    z-index:1000; box-shadow:0 6px 16px rgba(0,0,0,.35); border:1px solid transparent;\n"
    "  }\n"
    "  .toast.show { top:10px; }\n"
    "  .toast.ok { background:var(--ok-bg); color:var(--ok-fg); border-color:#1f5233; }\n"
    "  .toast.err { background:var(--err-bg); color:var(--err-fg); border-color:#5a2530; }\n"
    "  .hidden { display:none; }\n"
    "  .code-box {\n"
    "    position:relative; margin-top:10px; word-break: break-all; font-size:11px;\n"
    "    font-family:'Cascadia Code', Consolas, monospace; background:var(--surface);\n"
    "    border:1px solid var(--border); padding:8px 32px 8px 8px; border-radius:var(--radius-sm);\n"
    "    color:var(--text-dim);\n"
    "  }\n"
    "  .copy-btn {\n"
    "    position:absolute; top:6px; right:6px; width:22px; height:22px; padding:0;\n"
    "    display:flex; align-items:center; justify-content:center; background:var(--surface-2);\n"
    "    border:1px solid var(--border); border-radius:6px; cursor:pointer; color:var(--text-dim);\n"
    "    transition: background .15s ease, color .15s ease;\n"
    "  }\n"
    "  .copy-btn:hover { background:#383c46; color:var(--text); }\n"
    "  .copy-btn svg { width:12px; height:12px; fill:currentColor; }\n"
    "  .check-row {\n"
    "    display:flex; align-items:center; gap:10px; margin-bottom:2px; padding:8px 4px;\n"
    "    border-radius:var(--radius-sm); transition:background .15s ease;\n"
    "  }\n"
    "  .check-row:hover { background:var(--surface); }\n"
    "  .check-row input[type=checkbox] {\n"
    "    appearance:none; -webkit-appearance:none; position:relative; flex-shrink:0;\n"
    "    width:34px; height:20px; background:var(--surface-2); border:1px solid var(--border);\n"
    "    border-radius:999px; cursor:pointer; transition: background .15s ease, border-color .15s ease;\n"
    "    margin-top:0;\n"
    "  }\n"
    "  .check-row input[type=checkbox]::after {\n"
    "    content:''; position:absolute; top:1px; left:1px; width:16px; height:16px; border-radius:50%;\n"
    "    background:#c7c9d1; transition: transform .15s ease, background .15s ease;\n"
    "  }\n"
    "  .check-row input[type=checkbox]:checked { background:var(--accent); border-color:var(--accent); }\n"
    "  .check-row input[type=checkbox]:checked::after { transform:translateX(14px); background:#fff; }\n"
    "  .check-row span { display:flex; flex-direction:column; }\n"
    "  .check-row small { color:var(--text-dim); font-size:11px; margin-top:2px; }\n"
    "  .settings-list { flex:1 1 auto; min-height:0; overflow-y:auto; padding-right:4px; }\n"
    "  .settings-list::-webkit-scrollbar { width:6px; }\n"
    "  .settings-list::-webkit-scrollbar-thumb { background:var(--border); border-radius:3px; }\n"
    "  .settings-list .check-row:first-child { margin-top:0; }\n"
    "  .preset-row {\n"
    "    display:flex; align-items:center; gap:6px; margin-bottom:6px; padding:6px 8px;\n"
    "    background:var(--surface); border:1px solid var(--border); border-radius:var(--radius-sm);\n"
    "  }\n"
    "  .preset-name { flex:1; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; font-size:12px; }\n"
    "  .preset-row button { padding:5px 12px; flex-shrink:0; font-size:11px; }\n"
    "  .preset-delete {\n"
    "    display:flex; align-items:center; justify-content:center; padding:5px 7px;\n"
    "    background:transparent; border-color:#5a2530; color:var(--err-fg);\n"
    "  }\n"
    "  .preset-delete:hover { background:var(--err-bg); }\n"
    "  .preset-delete svg { width:12px; height:12px; fill:currentColor; }\n"
    "  .preset-empty { color:var(--text-dim); font-size:12px; text-align:center; padding:12px 0; }\n"
    "  p { margin:8px 0; color:var(--text-dim); line-height:1.5; }\n"
    "</style>\n"
    "</head>\n"
    "<body>\n"
    "  <div class='row'>\n"
    "    <label for='profileTrigger'>Profile</label>\n"
    "    <select id='profile' class='native-select'></select>\n"
    "    <div class='dropdown' id='profileDropdown'>\n"
    "      <button type='button' class='dropdown-trigger' id='profileTrigger'>\n"
    "        <span id='profileLabel'>Loading...</span>\n"
    "        <svg class='chevron' viewBox='0 0 24 24'><path d='M7 10l5 5 5-5z'/></svg>\n"
    "      </button>\n"
    "      <div class='dropdown-menu' id='profileMenu'></div>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <div class='tabs'>\n"
    "    <div class='tab active' data-tab='import'>Import</div>\n"
    "    <div class='tab' data-tab='export'>Export</div>\n"
    "    <div class='tab' data-tab='presets'>Presets</div>\n"
    "    <div class='tab' data-tab='settings'>Settings</div>\n"
    "    <div class='tab' data-tab='help'>Help</div>\n"
    "    <div class='tab' data-tab='about'>About</div>\n"
    "  </div>\n"
    "\n"
    "  <div class='panel active' id='panel-import'>\n"
    "    <div class='row'>\n"
    "      <input type='text' id='importInput' placeholder='Enter your code...'>\n"
    "      <button id='btnImport'>Import</button>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <div class='panel' id='panel-export'>\n"
    "    <button id='btnExport'>Export</button>\n"
    "    <div class='code-box hidden' id='exportResult'>\n"
    "      <button class='copy-btn' id='btnCopy' title='Copy'>\n"
    "        <svg viewBox='0 0 24 24'><path d='M16 1H4c-1.1 0-2 .9-2 2v14h2V3h12V1zm3 4H8c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h11c1.1 0 2-.9 2-2V7c0-1.1-.9-2-2-2zm0 16H8V7h11v14z'/></svg>\n"
    "      </button>\n"
    "      <span id='exportCode'></span>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <div class='panel' id='panel-presets'>\n"
    "    <div class='row'>\n"
    "      <input type='text' id='presetNameInput' placeholder='Preset name...'>\n"
    "      <button id='btnSavePreset'>Save</button>\n"
    "    </div>\n"
    "    <div class='settings-list' id='presetList'></div>\n"
    "  </div>\n"
    "\n"
    "  <div class='panel' id='panel-settings'>\n"
    "    <div class='settings-list'>\n"
    "    <div class='check-row'>\n"
    "      <input type='checkbox' id='optDisplay' checked>\n"
    "      <span>Display<small>Exports brightness</small></span>\n"
    "    </div>\n"
    "    <div class='check-row'>\n"
    "      <input type='checkbox' id='optDisplaySet' checked>\n"
    "      <span>Display Settings<small>Exports aspect ratio and FOV</small></span>\n"
    "    </div>\n"
    "    <div class='check-row'>\n"
    "      <input type='checkbox' id='optAudio' checked>\n"
    "      <span>Audio<small>Exports audio settings</small></span>\n"
    "    </div>\n"
    "    <div class='check-row'>\n"
    "      <input type='checkbox' id='optAccessibility' checked>\n"
    "      <span>Accessibility<small>Exports accessibility settings (like the colors)</small></span>\n"
    "    </div>\n"
    "    <div class='check-row'>\n"
    "      <input type='checkbox' id='optInput' checked>\n"
    "      <span>Input<small>Exports the input settings (currently only the sensitivity)</small></span>\n"
    "    </div>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <div class='panel' id='panel-help'>\n"
    "    <p>If you're having trouble finding the correct profile, just apply the config to all of them.</p>\n"
    "    <p>If the profile list is empty, the game is not installed.</p>\n"
    "  </div>\n"
    "\n"
    "  <div class='panel' id='panel-about'>\n"
    "    <p>Made by: @NotStrahinja on GitHub</p>\n"
    "    <p>Version: v2.1</p>\n"
    "  </div>\n"
    "\n"
    "  <div id='toast' class='toast'></div>\n"
    "\n"
    "<script>\n"
    "  let exportedCode = '';\n"
    "\n"
    "  function showToast(msg, ok) {\n"
    "    const t = document.getElementById('toast');\n"
    "    t.textContent = msg;\n"
    "    t.className = 'toast show ' + (ok ? 'ok' : 'err');\n"
    "    clearTimeout(t._timer);\n"
    "    t._timer = setTimeout(() => t.classList.remove('show'), 3000);\n"
    "  }\n"
    "\n"
    "  document.querySelectorAll('.tab').forEach(tab => {\n"
    "    tab.addEventListener('click', () => switchTab(tab.dataset.tab));\n"
    "  });\n"
    "\n"
    "  window.getProfiles().then(profiles => {\n"
    "    const sel = document.getElementById('profile');\n"
    "    const trigger = document.getElementById('profileTrigger');\n"
    "    const label = document.getElementById('profileLabel');\n"
    "    const menu = document.getElementById('profileMenu');\n"
    "\n"
    "    if (profiles.length === 0) {\n"
    "      const opt = document.createElement('option');\n"
    "      opt.textContent = 'No profiles found';\n"
    "      sel.appendChild(opt);\n"
    "      sel.disabled = true;\n"
    "      label.textContent = 'No profiles found';\n"
    "      trigger.disabled = true;\n"
    "      const empty = document.createElement('div');\n"
    "      empty.className = 'dropdown-empty';\n"
    "      empty.textContent = 'No profiles found';\n"
    "      menu.appendChild(empty);\n"
    "      return;\n"
    "    }\n"
    "\n"
    "    profiles.forEach((p, i) => {\n"
    "      const opt = document.createElement('option');\n"
    "      opt.value = i;\n"
    "      opt.textContent = p;\n"
    "      sel.appendChild(opt);\n"
    "\n"
    "      const item = document.createElement('div');\n"
    "      item.className = 'dropdown-item' + (i === 0 ? ' selected' : '');\n"
    "      item.textContent = p;\n"
    "      item.dataset.value = i;\n"
    "      item.addEventListener('click', () => selectProfile(i, p));\n"
    "      menu.appendChild(item);\n"
    "    });\n"
    "\n"
    "    label.textContent = profiles[0];\n"
    "  });\n"
    "\n"
    "  function selectProfile(idx, name) {\n"
    "    document.getElementById('profile').value = idx;\n"
    "    document.getElementById('profileLabel').textContent = name;\n"
    "    document.querySelectorAll('#profileMenu .dropdown-item').forEach(el => {\n"
    "      el.classList.toggle('selected', el.dataset.value == idx);\n"
    "    });\n"
    "    closeProfileDropdown();\n"
    "  }\n"
    "\n"
    "  function openProfileDropdown() {\n"
    "    document.getElementById('profileDropdown').classList.add('open');\n"
    "  }\n"
    "  function closeProfileDropdown() {\n"
    "    document.getElementById('profileDropdown').classList.remove('open');\n"
    "  }\n"
    "\n"
    "  document.getElementById('profileTrigger').addEventListener('click', (e) => {\n"
    "    e.stopPropagation();\n"
    "    if (document.getElementById('profileTrigger').disabled) return;\n"
    "    const dd = document.getElementById('profileDropdown');\n"
    "    dd.classList.contains('open') ? closeProfileDropdown() : openProfileDropdown();\n"
    "  });\n"
    "  document.addEventListener('click', (e) => {\n"
    "    const dd = document.getElementById('profileDropdown');\n"
    "    if (!dd.contains(e.target)) closeProfileDropdown();\n"
    "  });\n"
    "  document.addEventListener('keydown', (e) => {\n"
    "    if (e.key === 'Escape') closeProfileDropdown();\n"
    "  });\n"
    "\n"
    "  document.getElementById('btnImport').addEventListener('click', () => {\n"
    "    const idx = parseInt(document.getElementById('profile').value, 10);\n"
    "    const code = document.getElementById('importInput').value.trim();\n"
    "    if (code.length <= 30) {\n"
    "      showToast('Invalid config.', false);\n"
    "      return;\n"
    "    }\n"
    "    window.importConfig(idx, code).then(res => {\n"
    "      if (res.ok) showToast('Config imported.', true);\n"
    "      else showToast(res.error, false);\n"
    "    });\n"
    "  });\n"
    "\n"
    "  const EXPORT_DISPLAY = 1 << 0;\n"
    "  const EXPORT_DISPLAY_SET = 1 << 1;\n"
    "  const EXPORT_AUDIO = 1 << 2;\n"
    "  const EXPORT_ACCESSIBILITY = 1 << 3;\n"
    "  const EXPORT_INPUT = 1 << 4;\n"
    "\n"
    "  function getExportMask() {\n"
    "    let mask = 0;\n"
    "    if (document.getElementById('optDisplay').checked) mask |= EXPORT_DISPLAY;\n"
    "    if (document.getElementById('optDisplaySet').checked) mask |= EXPORT_DISPLAY_SET;\n"
    "    if (document.getElementById('optAudio').checked) mask |= EXPORT_AUDIO;\n"
    "    if (document.getElementById('optAccessibility').checked) mask |= EXPORT_ACCESSIBILITY;\n"
    "    if (document.getElementById('optInput').checked) mask |= EXPORT_INPUT;\n"
    "    return mask;\n"
    "  }\n"
    "\n"
    "  document.getElementById('btnExport').addEventListener('click', () => {\n"
    "    const idx = parseInt(document.getElementById('profile').value, 10);\n"
    "    const mask = getExportMask();\n"
    "    if (mask === 0) {\n"
    "      showToast('Select at least one category in Settings.', false);\n"
    "      return;\n"
    "    }\n"
    "    window.exportConfig(idx, mask).then(res => {\n"
    "      if (res.ok) {\n"
    "        exportedCode = res.code;\n"
    "        document.getElementById('exportCode').textContent = exportedCode;\n"
    "        document.getElementById('exportResult').classList.remove('hidden');\n"
    "        showToast('Config exported.', true);\n"
    "      } else {\n"
    "        showToast(res.error, false);\n"
    "      }\n"
    "    });\n"
    "  });\n"
    "\n"
    "  function copyToClipboard(text) {\n"
    "    if (navigator.clipboard && navigator.clipboard.writeText) {\n"
    "      navigator.clipboard.writeText(text)\n"
    "        .then(() => showToast('Config copied.', true))\n"
    "        .catch(() => legacyCopy(text));\n"
    "    } else {\n"
    "      legacyCopy(text);\n"
    "    }\n"
    "  }\n"
    "\n"
    "  function legacyCopy(text) {\n"
    "    const ta = document.createElement('textarea');\n"
    "    ta.value = text;\n"
    "    ta.style.position = 'fixed';\n"
    "    ta.style.top = '-1000px';\n"
    "    document.body.appendChild(ta);\n"
    "    ta.focus();\n"
    "    ta.select();\n"
    "    let ok = false;\n"
    "    try { ok = document.execCommand('copy'); } catch (e) { ok = false; }\n"
    "    document.body.removeChild(ta);\n"
    "    showToast(ok ? 'Config copied.' : 'Copy failed.', ok);\n"
    "  }\n"
    "\n"
    "  document.getElementById('btnCopy').addEventListener('click', () => {\n"
    "    copyToClipboard(exportedCode);\n"
    "  });\n"
    "  function switchTab(name) {\n"
    "    document.querySelectorAll('.tab').forEach(t => t.classList.remove('active'));\n"
    "    document.querySelectorAll('.panel').forEach(p => p.classList.remove('active'));\n"
    "    document.querySelector('.tab[data-tab=' + name + ']').classList.add('active');\n"
    "    document.getElementById('panel-' + name).classList.add('active');\n"
    "  }\n"
    "\n"
    "  function renderPresets(presets) {\n"
    "    const list = document.getElementById('presetList');\n"
    "    list.innerHTML = '';\n"
    "\n"
    "    if (presets.length === 0) {\n"
    "      const empty = document.createElement('div');\n"
    "      empty.className = 'preset-empty';\n"
    "      empty.textContent = 'No saved presets.';\n"
    "      list.appendChild(empty);\n"
    "      return;\n"
    "    }\n"
    "\n"
    "    presets.forEach(p => {\n"
    "      const row = document.createElement('div');\n"
    "      row.className = 'preset-row';\n"
    "\n"
    "      const name = document.createElement('span');\n"
    "      name.className = 'preset-name';\n"
    "      name.textContent = p.name;\n"
    "      name.title = p.name;\n"
    "\n"
    "      const loadBtn = document.createElement('button');\n"
    "      loadBtn.textContent = 'Load';\n"
    "      loadBtn.addEventListener('click', () => {\n"
    "        document.getElementById('importInput').value = p.code;\n"
    "        switchTab('import');\n"
    "        showToast('Preset loaded into Import.', true);\n"
    "      });\n"
    "\n"
    "      const delBtn = document.createElement('button');\n"
    "      delBtn.className = 'preset-delete';\n"
    "      delBtn.title = 'Delete';\n"
    "      delBtn.innerHTML = \"<svg viewBox='0 0 24 24'><path d='M9 3v1H4v2h1v14c0 1.1.9 2 2 2h10c1.1 0 2-.9 2-2V6h1V4h-5V3H9zm2 5h2v10h-2V8zm-4 0h2v10H7V8zm8 0h2v10h-2V8z'/></svg>\";\n"
    "      delBtn.addEventListener('click', () => {\n"
    "        window.deletePreset(p.name).then(res => {\n"
    "          if (res.ok) { showToast('Preset deleted.', true); refreshPresets(); }\n"
    "          else showToast(res.error, false);\n"
    "        });\n"
    "      });\n"
    "\n"
    "      row.appendChild(name);\n"
    "      row.appendChild(loadBtn);\n"
    "      row.appendChild(delBtn);\n"
    "      list.appendChild(row);\n"
    "    });\n"
    "  }\n"
    "\n"
    "  function refreshPresets() {\n"
    "    window.getPresets().then(renderPresets);\n"
    "  }\n"
    "\n"
    "  refreshPresets();\n"
    "\n"
    "  document.getElementById('btnSavePreset').addEventListener('click', () => {\n"
    "    const name = document.getElementById('presetNameInput').value.trim();\n"
    "    if (!name) {\n"
    "      showToast('Enter a preset name.', false);\n"
    "      return;\n"
    "    }\n"
    "    if (!exportedCode) {\n"
    "      showToast('Export a config first.', false);\n"
    "      return;\n"
    "    }\n"
    "    window.savePreset(name, exportedCode).then(res => {\n"
    "      if (res.ok) {\n"
    "        showToast('Preset saved.', true);\n"
    "        document.getElementById('presetNameInput').value = '';\n"
    "        refreshPresets();\n"
    "      } else {\n"
    "        showToast(res.error, false);\n"
    "      }\n"
    "    });\n"
    "  });\n"
    "</script>\n"
    "</body>\n"
    "</html>\n";

#endif // UI_HTML_H
