#ifndef UI_HTML_H
#define UI_HTML_H

static const char UI_HTML[] =
"<!DOCTYPE html>\n"
"<html>\n"
"<head>\n"
"<meta charset='utf-8'>\n"
"<style>\n"
"  html, body { height:100%; overflow:hidden; }\n"
"  body { font-family: system-ui, sans-serif; background:#1e1e1e; color:#eee; margin:0; padding:12px; font-size:13px; box-sizing:border-box; }\n"
"  select, input, button, textarea { font-family: inherit; }\n"
"  .row { display:flex; gap:8px; align-items:center; margin-bottom:8px; }\n"
"  select { flex:1; background:#2b2b2b; color:#eee; border:1px solid #444; padding:4px; border-radius:4px; }\n"
"  .tabs { display:flex; border-bottom:1px solid #444; margin-bottom:10px; }\n"
"  .tab { padding:6px 12px; cursor:pointer; opacity:.6; user-select:none; }\n"
"  .tab.active { opacity:1; border-bottom:2px solid #4caf50; }\n"
"  .panel { display:none; }\n"
"  .panel.active { display:block; }\n"
"  button { background:#3a3a3a; color:#eee; border:1px solid #555; border-radius:4px; padding:6px 14px; cursor:pointer; }\n"
"  button:hover { background:#4a4a4a; }\n"
"  textarea, input[type=text] { width:100%; background:#2b2b2b; color:#eee; border:1px solid #444; border-radius:4px; padding:6px; box-sizing:border-box; }\n"
"  .toast { position:fixed; top:-40px; left:12px; right:12px; padding:6px; border-radius:4px; font-size:12px; text-align:center; transition: top 0.2s ease; z-index:1000; }\n"
"  .toast.show { top:8px; }\n"
"  .toast.ok { background:#2e4d2e; color:#9ef79e; }\n"
"  .toast.err { background:#4d2e2e; color:#f79e9e; }\n"
"  .hidden { display:none; }\n"
"  .code-box { position:relative; margin-top:10px; word-break: break-all; font-size:11px; background:#2b2b2b; padding:6px 30px 6px 6px; border-radius:4px; }\n"
"  .copy-btn { position:absolute; top:4px; right:4px; width:20px; height:20px; padding:0; display:flex; align-items:center; justify-content:center; background:#3a3a3a; border:1px solid #555; border-radius:4px; cursor:pointer; color:#eee; }\n"
"  .copy-btn:hover { background:#4a4a4a; }\n"
"  .copy-btn svg { width:12px; height:12px; fill:currentColor; }\n"
"  .check-row { display:flex; align-items:flex-start; gap:8px; margin-bottom:8px; cursor:pointer; }\n"
"  .check-row input { margin-top:2px; }\n"
"  .check-row span { display:flex; flex-direction:column; }\n"
"  .check-row small { color:#999; font-size:11px; margin-top:2px; }\n"
"  .settings-list { max-height:140px; overflow-y:auto; padding-right:6px; }\n"
"  p { margin:6px 0; }\n"
"</style>\n"
"</head>\n"
"<body>\n"
"  <div class='row'>\n"
"    <label for='profile'>Profile</label>\n"
"    <select id='profile'></select>\n"
"  </div>\n"
"\n"
"  <div class='tabs'>\n"
"    <div class='tab active' data-tab='import'>Import</div>\n"
"    <div class='tab' data-tab='export'>Export</div>\n"
"    <div class='tab' data-tab='settings'>Settings</div>\n"
"    <div class='tab' data-tab='help'>Help</div>\n"
"    <div class='tab' data-tab='about'>About</div>\n"
"  </div>\n"
"\n"
"  <div class='panel active' id='panel-import'>\n"
"    <input type='text' id='importInput' placeholder='Enter your code...'>\n"
"    <div class='row' style='margin-top:8px;'>\n"
"      <button id='btnImport'>Import</button>\n"
"    </div>\n"
"  </div>\n"
"\n"
"  <div class='panel' id='panel-export'>\n"
"    <button id='btnExport'>Export</button>\n"
"    <div class='code-box hidden' id='exportResult'>\n"
"      <button class='copy-btn' id='btnCopy' title='Copy'>\n"
"        <svg viewBox='0 0 24 24'><path d='M16 1H4c-1.1 0-2 .9-2 2v14h2V3h12V1zm3 4H8c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h11c1.1 0 2-.9 2-2V7c0-1.1-.9-2-2-2zm0 16H8V7h11v14z'/></svg>\n"
"      </button>\n"
"      <span id='exportCode'></span>\n"
"    </div>\n"
"  </div>\n"
"\n"
"  <div class='panel' id='panel-settings'>\n"
"    <div class='settings-list'>\n"
"    <label class='check-row'>\n"
"      <input type='checkbox' id='optDisplay' checked>\n"
"      <span>Display<small>Exports brightness</small></span>\n"
"    </label>\n"
"    <label class='check-row'>\n"
"      <input type='checkbox' id='optDisplaySet' checked>\n"
"      <span>Display Settings<small>Exports aspect ratio and FOV</small></span>\n"
"    </label>\n"
"    <label class='check-row'>\n"
"      <input type='checkbox' id='optAudio' checked>\n"
"      <span>Audio<small>Exports audio settings</small></span>\n"
"    </label>\n"
"    <label class='check-row'>\n"
"      <input type='checkbox' id='optAccessibility' checked>\n"
"      <span>Accessibility<small>Exports accessibility settings (like the colors)</small></span>\n"
"    </label>\n"
"    <label class='check-row'>\n"
"      <input type='checkbox' id='optInput' checked>\n"
"      <span>Input<small>Exports the input settings (currently only the sensitivity)</small></span>\n"
"    </label>\n"
"    </div>\n"
"  </div>\n"
"\n"
"  <div class='panel' id='panel-help'>\n"
"    <p>If you're having trouble finding the correct profile, just apply the config to all of them.</p>\n"
"    <p>If the profile list is empty, the game is not installed.</p>\n"
"  </div>\n"
"\n"
"  <div class='panel' id='panel-about'>\n"
"    <p>Made by: @gottvonterrorismus</p>\n"
"    <p>Version: v1.2</p>\n"
"  </div>\n"
"\n"
"  <div id='toast' class='toast'></div>\n"
"\n"
"<script>\n"
"  let exportedCode = '';\n"
"\n"
"  function showToast(msg, ok) {\n"
"    const t = document.getElementById('toast');\n"
"    t.textContent = msg;\n"
"    t.className = 'toast show ' + (ok ? 'ok' : 'err');\n"
"    clearTimeout(t._timer);\n"
"    t._timer = setTimeout(() => t.classList.remove('show'), 3000);\n"
"  }\n"
"\n"
"  document.querySelectorAll('.tab').forEach(tab => {\n"
"    tab.addEventListener('click', () => {\n"
"      document.querySelectorAll('.tab').forEach(t => t.classList.remove('active'));\n"
"      document.querySelectorAll('.panel').forEach(p => p.classList.remove('active'));\n"
"      tab.classList.add('active');\n"
"      document.getElementById('panel-' + tab.dataset.tab).classList.add('active');\n"
"    });\n"
"  });\n"
"\n"
"  window.getProfiles().then(profiles => {\n"
"    const sel = document.getElementById('profile');\n"
"    if (profiles.length === 0) {\n"
"      const opt = document.createElement('option');\n"
"      opt.textContent = 'No profiles found';\n"
"      sel.appendChild(opt);\n"
"      sel.disabled = true;\n"
"      return;\n"
"    }\n"
"    profiles.forEach((p, i) => {\n"
"      const opt = document.createElement('option');\n"
"      opt.value = i;\n"
"      opt.textContent = p;\n"
"      sel.appendChild(opt);\n"
"    });\n"
"  });\n"
"\n"
"  document.getElementById('btnImport').addEventListener('click', () => {\n"
"    const idx = parseInt(document.getElementById('profile').value, 10);\n"
"    const code = document.getElementById('importInput').value.trim();\n"
"    if (code.length <= 30) {\n"
"      showToast('Invalid config.', false);\n"
"      return;\n"
"    }\n"
"    window.importConfig(idx, code).then(res => {\n"
"      if (res.ok) showToast('Config imported.', true);\n"
"      else showToast(res.error, false);\n"
"    });\n"
"  });\n"
"\n"
"  const EXPORT_DISPLAY = 1 << 0;\n"
"  const EXPORT_DISPLAY_SET = 1 << 1;\n"
"  const EXPORT_AUDIO = 1 << 2;\n"
"  const EXPORT_ACCESSIBILITY = 1 << 3;\n"
"  const EXPORT_INPUT = 1 << 4;\n"
"\n"
"  function getExportMask() {\n"
"    let mask = 0;\n"
"    if (document.getElementById('optDisplay').checked) mask |= EXPORT_DISPLAY;\n"
"    if (document.getElementById('optDisplaySet').checked) mask |= EXPORT_DISPLAY_SET;\n"
"    if (document.getElementById('optAudio').checked) mask |= EXPORT_AUDIO;\n"
"    if (document.getElementById('optAccessibility').checked) mask |= EXPORT_ACCESSIBILITY;\n"
"    if (document.getElementById('optInput').checked) mask |= EXPORT_INPUT;\n"
"    return mask;\n"
"  }\n"
"\n"
"  document.getElementById('btnExport').addEventListener('click', () => {\n"
"    const idx = parseInt(document.getElementById('profile').value, 10);\n"
"    const mask = getExportMask();\n"
"    if (mask === 0) {\n"
"      showToast('Select at least one category in Settings.', false);\n"
"      return;\n"
"    }\n"
"    window.exportConfig(idx, mask).then(res => {\n"
"      if (res.ok) {\n"
"        exportedCode = res.code;\n"
"        document.getElementById('exportCode').textContent = exportedCode;\n"
"        document.getElementById('exportResult').classList.remove('hidden');\n"
"        showToast('Config exported.', true);\n"
"      } else {\n"
"        showToast(res.error, false);\n"
"      }\n"
"    });\n"
"  });\n"
"\n"
"  function copyToClipboard(text) {\n"
"    if (navigator.clipboard && navigator.clipboard.writeText) {\n"
"      navigator.clipboard.writeText(text)\n"
"        .then(() => showToast('Config copied.', true))\n"
"        .catch(() => legacyCopy(text));\n"
"    } else {\n"
"      legacyCopy(text);\n"
"    }\n"
"  }\n"
"\n"
"  function legacyCopy(text) {\n"
"    const ta = document.createElement('textarea');\n"
"    ta.value = text;\n"
"    ta.style.position = 'fixed';\n"
"    ta.style.top = '-1000px';\n"
"    document.body.appendChild(ta);\n"
"    ta.focus();\n"
"    ta.select();\n"
"    let ok = false;\n"
"    try { ok = document.execCommand('copy'); } catch (e) { ok = false; }\n"
"    document.body.removeChild(ta);\n"
"    showToast(ok ? 'Config copied.' : 'Copy failed.', ok);\n"
"  }\n"
"\n"
"  document.getElementById('btnCopy').addEventListener('click', () => {\n"
"    copyToClipboard(exportedCode);\n"
"  });\n"
"</script>\n"
"</body>\n"
"</html>\n";

#endif // UI_HTML_H
